/*
  # Seed Services and Team Data
  
  This migration populates the legal_services and team_members tables with initial data
  from the existing static data files (servicesData.ts and teamData.ts).
  
  ## Services Added (10 total)
  - Civil and Criminal Litigation
  - Alternative Dispute Resolution (ADR)
  - Commercial and Corporate Law
  - Bank Securities, Conveyancing and Real Estate Law
  - Employment and Labour Law
  - Family Law
  - Consultancy
  - Health and Medical Law
  - Finance and Banking Law
  - Insurance and Personal Injury Law
  
  ## Team Members Added (9 total)
  - Partners: Sospeter Opondo Aming'a, Paul Kiranga, Faith Simiyu, Angela Omuya
  - Associates: Kennedy Muriuki Kiranga, Geoffrey Otieno, Loise Njeri Njoroge
  - Consultants: Justus Njoroge
  - Assistants: Shallet Wangui Katiku
*/

-- Insert all services from servicesData.ts
INSERT INTO legal_services (title, description, overview, icon_name, header_image, key_services, why_choose_us, process, is_active) VALUES
('Civil and Criminal Litigation', 
 'Expert representation in civil disputes and criminal defense matters with proven track record in Kenyan courts.', 
 'Our litigation practice provides comprehensive representation in both civil and criminal matters. We handle complex disputes with strategic thinking and aggressive advocacy to achieve favorable outcomes for our clients.', 
 'Scale', 
 'https://images.pexels.com/photos/5668882/pexels-photo-5668882.jpeg?auto=compress&cs=tinysrgb&w=1200&h=600&fit=crop', 
 E'Civil Litigation\nCriminal Defense\nCommercial Disputes\nContract Disputes\nTort Claims\nAppeals\nInjunctive Relief\nDebt Recovery\nProperty Disputes\nConstitutional Matters\nJudicial Review\nClass Action Suits', 
 E'Proven Track Record: Over 500 successful cases with extensive experience in Kenyan courts at all levels.\n\nStrategic Litigation: We develop comprehensive litigation strategies that consider both legal and business implications.\n\nExperienced Trial Lawyers: Our team includes seasoned trial lawyers with deep courtroom experience.', 
 E'Case Assessment: Comprehensive evaluation of your case merits and potential outcomes.\n\nStrategy Development: Development of tailored litigation strategy aligned with your objectives.\n\nPre-trial Preparation: Thorough preparation including evidence gathering and witness preparation.\n\nCourt Representation: Aggressive representation in court proceedings with experienced advocates.\n\nPost-judgment Support: Assistance with judgment enforcement and appeals if necessary.', 
 true),

('Alternative Dispute Resolution (ADR) Arbitration, Mediation and Structured Negotiation', 
 'Arbitration, mediation and structured negotiation services for efficient dispute resolution.', 
 'Our ADR practice offers efficient alternatives to traditional litigation, helping clients resolve disputes through arbitration, mediation, and structured negotiation processes that save time and costs.', 
 'Users', 
 'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=1200&h=600&fit=crop', 
 E'Commercial Arbitration\nFamily Mediation\nWorkplace Mediation\nConstruction Arbitration\nInternational Arbitration\nStructured Negotiation\nConciliation Services\nExpert Determination\nSettlement Conferences\nMulti-party Mediation\nOnline Dispute Resolution\nArbitrator Services', 
 E'Certified Mediators: Our team includes certified mediators and arbitrators with extensive ADR experience.\n\nCost-Effective Solutions: ADR processes typically cost less and resolve faster than traditional litigation.\n\nConfidential Process: ADR proceedings are private and confidential, protecting your business interests.', 
 E'Dispute Analysis: Assessment of the dispute and recommendation of appropriate ADR method.\n\nProcess Selection: Selection of the most suitable ADR process for your specific situation.\n\nPreparation: Thorough preparation of your case for the ADR proceedings.\n\nADR Proceedings: Skilled representation during arbitration, mediation or negotiation.\n\nImplementation: Assistance with implementation and enforcement of ADR outcomes.', 
 true),

('Commercial and Corporate Law', 
 'Comprehensive corporate legal services including company formation, governance, and commercial transactions.', 
 'Our commercial and corporate law practice provides comprehensive legal services to businesses across Kenya. We assist companies in navigating complex regulatory environments and structuring transactions for growth.', 
 'Building', 
 'https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?auto=compress&cs=tinysrgb&w=1200&h=600&fit=crop', 
 E'Company Formation\nCorporate Governance\nMergers & Acquisitions\nJoint Ventures\nCommercial Contracts\nSecurities Law\nCorporate Restructuring\nDue Diligence\nRegulatory Compliance\nBoard Advisory\nShareholder Agreements\nCorporate Finance', 
 E'Business-Focused Approach: We understand business needs and provide practical legal solutions.\n\nRegulatory Expertise: Deep knowledge of Kenyan corporate law and regulatory requirements.\n\nTransaction Experience: Extensive experience in complex commercial transactions and deals.', 
 E'Business Consultation: Understanding your business objectives and legal requirements.\n\nLegal Structure: Designing optimal legal structures for your business operations.\n\nDocumentation: Preparation of all necessary corporate and commercial documents.\n\nImplementation: Execution of corporate strategies and transaction completion.\n\nOngoing Support: Continuous legal support for corporate governance and compliance.', 
 true),

('Bank Securities, Conveyancing and Real Estate Law', 
 'Property transactions, land disputes, conveyancing, and banking securities legal services.', 
 'Our real estate and banking securities practice covers all aspects of property law and banking securities in Kenya. We provide comprehensive services for property transactions and banking security arrangements.', 
 'Home', 
 'https://images.pexels.com/photos/280229/pexels-photo-280229.jpeg?auto=compress&cs=tinysrgb&w=1200&h=600&fit=crop', 
 E'Property Conveyancing\nLand Title Verification\nBanking Securities\nMortgage Documentation\nLease Agreements\nProperty Development\nLand Disputes\nSecurity Perfection\nProperty Finance\nReal Estate Investment\nLandlord-Tenant Law\nZoning Applications', 
 E'Local Expertise: Deep understanding of Kenyan land law and banking regulations.\n\nDue Diligence Excellence: Thorough property searches and security verification processes.\n\nBanking Relationships: Strong relationships with major banks and financial institutions.', 
 E'Property/Security Search: Comprehensive verification of property titles and security interests.\n\nDue Diligence: Thorough investigation of legal and financial aspects.\n\nDocumentation: Preparation of all necessary legal documents and agreements.\n\nRegistration: Handling registration with relevant authorities and institutions.\n\nPost-transaction Support: Ongoing support for property management and security enforcement.', 
 true),

('Employment and Labour Law', 
 'Employment contracts, workplace disputes, labor relations, and human resources legal guidance.', 
 'Our employment and labour law practice serves both employers and employees in navigating the complex landscape of Kenyan labor law and employment regulations.', 
 'Briefcase', 
 'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=1200&h=600&fit=crop', 
 E'Employment Contracts\nWorkplace Policies\nDisciplinary Procedures\nWrongful Termination\nDiscrimination Claims\nWage and Hour Issues\nWorkers Compensation\nUnion Relations\nEmployment Compliance\nExecutive Compensation\nNon-compete Agreements\nWorkplace Safety', 
 E'Dual Perspective: We represent both employers and employees with balanced expertise.\n\nRegulatory Knowledge: Up-to-date knowledge of Kenyan employment law and regulations.\n\nPractical Solutions: Business-oriented solutions to employment challenges.', 
 E'Employment Consultation: Assessment of employment issues and legal options available.\n\nLegal Analysis: Analysis of employment contracts, policies, and applicable laws.\n\nStrategy Development: Development of strategic approach to resolve employment matters.\n\nImplementation: Implementation through negotiation, mediation, or litigation.\n\nCompliance Support: Ongoing support to ensure compliance and prevent future issues.', 
 true),

('Family Law', 
 'Divorce proceedings, child custody, adoption, matrimonial property, and family dispute resolution.', 
 'Our family law practice provides compassionate legal services for families, handling sensitive matters with discretion while prioritizing the best interests of children and families.', 
 'Heart', 
 'https://images.pexels.com/photos/1648776/pexels-photo-1648776.jpeg?auto=compress&cs=tinysrgb&w=1200&h=600&fit=crop', 
 E'Divorce and Separation\nChild Custody\nChild Support\nAdoption Proceedings\nMatrimonial Property\nPrenuptial Agreements\nDomestic Violence\nGuardianship\nPaternity Issues\nFamily Mediation\nSuccession Planning\nMarriage Contracts', 
 E'Compassionate Approach: Understanding and supportive guidance through difficult family matters.\n\nChild-Focused: Always prioritizing the best interests of children in all proceedings.\n\nConfidential Service: Strict confidentiality and discrete handling of sensitive matters.', 
 E'Confidential Consultation: Private consultation to understand your family situation and needs.\n\nCase Preparation: Gathering necessary documentation and evidence for your case.\n\nNegotiation: Attempting amicable agreements through negotiation and mediation.\n\nCourt Proceedings: Professional representation when court intervention is necessary.\n\nPost-decree Support: Ongoing support for enforcement and modification of orders.', 
 true),

('Consultancy', 
 'Legal consultancy services providing strategic advice and guidance across various legal matters.', 
 'Our consultancy services provide strategic legal advice and guidance to individuals, businesses, and organizations across various legal matters and industries.', 
 'HelpCircle', 
 'https://images.pexels.com/photos/3184430/pexels-photo-3184430.jpeg?auto=compress&cs=tinysrgb&w=1200&h=600&fit=crop', 
 E'Legal Strategy Consulting\nRisk Assessment\nCompliance Consulting\nBusiness Advisory\nLegal Audits\nPolicy Development\nTraining Services\nLegal Research\nRegulatory Guidance\nContract Advisory\nDispute Prevention\nLegal Opinions', 
 E'Strategic Thinking: We provide strategic legal advice that aligns with your business objectives.\n\nIndustry Knowledge: Deep understanding of various industries and their legal requirements.\n\nProactive Approach: Focus on preventing legal issues before they become problems.', 
 E'Needs Assessment: Understanding your specific consultancy needs and objectives.\n\nAnalysis: Comprehensive analysis of your legal and business situation.\n\nStrategy Development: Development of tailored strategies and recommendations.\n\nImplementation Support: Guidance and support during strategy implementation.\n\nOngoing Advisory: Continuous advisory support and strategy refinement.', 
 true),

('Health and Medical Law', 
 'Healthcare law, medical malpractice, regulatory compliance, and healthcare facility legal services.', 
 'Our health and medical law practice provides specialized legal services to healthcare providers, medical professionals, and healthcare institutions across Kenya.', 
 'Heart', 
 'https://images.pexels.com/photos/4021775/pexels-photo-4021775.jpeg?auto=compress&cs=tinysrgb&w=1200&h=600&fit=crop', 
 E'Medical Malpractice Defense\nHealthcare Regulatory Compliance\nMedical Licensing\nHealthcare Contracts\nPatient Rights\nMedical Ethics\nHealthcare Facility Licensing\nPharmaceutical Law\nMedical Device Regulation\nHealthcare Employment\nMedical Records\nHealthcare Disputes', 
 E'Medical Knowledge: Understanding of medical practices and healthcare regulations.\n\nRegulatory Expertise: Deep knowledge of healthcare regulatory requirements in Kenya.\n\nProfessional Network: Strong relationships with medical professionals and institutions.', 
 E'Healthcare Assessment: Assessment of healthcare legal and regulatory requirements.\n\nCompliance Review: Review of current compliance with healthcare regulations.\n\nRisk Mitigation: Development of strategies to mitigate healthcare legal risks.\n\nDocumentation: Preparation of healthcare policies, contracts, and procedures.\n\nOngoing Support: Continuous support for healthcare compliance and legal matters.', 
 true),

('Finance and Banking Law', 
 'Banking regulations, financial services law, fintech compliance, and financial institution legal services.', 
 'Our finance and banking law practice provides comprehensive legal services to banks, financial institutions, fintech companies, and clients with financial legal needs.', 
 'DollarSign', 
 'https://images.pexels.com/photos/4386321/pexels-photo-4386321.jpeg?auto=compress&cs=tinysrgb&w=1200&h=600&fit=crop', 
 E'Banking Regulations\nFinancial Services Licensing\nFintech Compliance\nSecurities Law\nCapital Markets\nBanking Litigation\nFinancial Contracts\nRegulatory Compliance\nAnti-Money Laundering\nConsumer Finance\nInvestment Advisory\nFinancial Restructuring', 
 E'Financial Expertise: Deep understanding of financial services and banking regulations.\n\nRegulatory Knowledge: Up-to-date knowledge of financial regulatory requirements.\n\nIndustry Relationships: Strong relationships with financial regulators and institutions.', 
 E'Financial Assessment: Assessment of financial legal and regulatory requirements.\n\nCompliance Strategy: Development of financial compliance and regulatory strategy.\n\nDocumentation: Preparation of financial agreements and regulatory filings.\n\nRegulatory Liaison: Liaison with financial regulators and authorities.\n\nOngoing Compliance: Continuous support for financial compliance and regulations.', 
 true),

('Insurance and Personal Injury Law', 
 'Insurance claims, personal injury litigation, motor vehicle accidents, and insurance coverage disputes.', 
 'Our insurance and personal injury practice provides comprehensive legal services for insurance claims, personal injury litigation, and insurance coverage disputes.', 
 'Shield', 
 'https://images.pexels.com/photos/5668858/pexels-photo-5668858.jpeg?auto=compress&cs=tinysrgb&w=1200&h=600&fit=crop', 
 E'Personal Injury Claims\nMotor Vehicle Accidents\nInsurance Coverage Disputes\nWorkers Compensation\nMedical Malpractice\nProduct Liability\nWrongful Death\nInsurance Bad Faith\nDisability Claims\nProperty Insurance\nProfessional Liability\nInsurance Defense', 
 E'Insurance Knowledge: Deep understanding of insurance law and coverage issues.\n\nTrial Experience: Extensive trial experience in personal injury and insurance cases.\n\nClient Advocacy: Strong advocacy for clients against insurance companies.', 
 E'Claim Assessment: Comprehensive assessment of insurance claims and personal injury cases.\n\nInvestigation: Thorough investigation of facts and circumstances.\n\nNegotiation: Skilled negotiation with insurance companies and opposing parties.\n\nLitigation: Aggressive litigation when fair settlement cannot be reached.\n\nRecovery: Assistance with claim recovery and settlement implementation.', 
 true);

-- Insert all team members from teamData.ts
INSERT INTO team_members (name, role, category, specialization, image, email, phone, qualifications, experience, achievements, description, expertise, education, admissions, languages, is_active) VALUES
('Sospeter Opondo Aming''a', 
 'Co-Founder & Managing Partner', 
 'Partners', 
 'Litigation & Dispute Resolution', 
 'https://i.postimg.cc/MGfCq6YL/7X2A2792.jpg', 
 'sospeter@soklaw.co.ke', 
 '0205285048', 
 E'LLB (Hons)\nDiploma in Law\nCertified Public Secretary\nManagement & Customer Care Training', 
 '10+ years of legal practice', 
 E'Successfully led high-profile litigation and dispute resolution matters\nHeaded legal departments in top organizations (KTDA, REAL Insurance, UAP Insurance)\nPublished articles in professional and corporate magazines\nFounder of County Legal Aid Bureau (CLAB) CSR initiative\nActive member of the Law Society of Kenya and East African Law Society', 
 'Sospeter Opondo Aming''a is the Co-Founder and Managing Partner of the Firm, where he leads the Litigation and Dispute Resolution department with a steadfast commitment to justice and the best interests of his clients. With over a decade of experience in legal practice and a strong corporate background, he brings both strategic insight and genuine compassion to every case he handles. His expertise spans litigation and out-of-court settlements in employment disputes, commercial matters, and personal injury claims. Before establishing the firm, Sospeter held senior positions in leading organizations, including Kenya Tea Development Agency (KTDA), REAL Insurance Company Ltd, and UAP Insurance Company Ltd, where he rose to head the legal department. This blend of corporate and legal experience equips him with a deep understanding of both the technical and human aspects of complex disputes. Beyond the courtroom, Sospeter is passionate about mentorship and giving back. He founded the County Legal Aid Bureau (CLAB), the firm''s flagship Corporate Social Responsibility program, which works to make legal support accessible to underserved communities.', 
 E'Litigation & Dispute Resolution\nEmployment Law\nCommercial Law\nPersonal Injury Claims\nOut-of-Court Settlements\nCorporate Legal Advisory', 
 E'University of Nairobi - Bachelor of Laws (LLB)\nKenya School of Law - Postgraduate Diploma in Law\nCertified Public Secretary (CPS-K)\nSpecialized Training - Management & Customer Care', 
 E'Advocate of the High Court of Kenya\nMember of Law Society of Kenya\nMember of East African Law Society\nCertified Public Secretary of Kenya', 
 'English, Swahili, Luo', 
 true),

('Paul Kiranga', 
 'Co-Founder & Partner', 
 'Partners', 
 'Bank Securities and Conveyancing', 
 'https://i.postimg.cc/v8KZvBN1/Whats-App-Image-2025-07-20-at-03-11-55.jpg', 
 'paul@soklaw.co.ke', 
 '020 528 5048', 
 E'LLB (Hons)\nDiploma in Law', 
 '5+ years in real estate, conveyancing, and bank securities practice', 
 E'Perfected securities for leading banks, including Bank of Baroda, Standard Chartered, and Guardian Bank\nSuccessfully advised on high-value mergers, acquisitions, and joint ventures\nProvided legal advisory on complex corporate and financing transactions\nActed for both Kenyan and international corporate clients across diverse sectors', 
 'Paul Kiranga is a Co-Founder and the Partner in charge of the Bank Securities and Conveyancing Department at SOKLaw. He holds a Bachelor of Laws (LL.B) degree from the University of Nairobi (2009) and a Postgraduate Diploma in Law from the Kenya School of Law (2010). He was admitted to the Roll of Advocates in 2011. Paul has gained extensive experience in real estate and conveyancing practice, as well as the perfection of securities. He previously served as an associate in charge of the Conveyancing and Bank Securities Department at Mucheru-Oyatta & Associates Advocates, where he perfected security documents on behalf of major banks in Kenya, including Bank of Baroda (K) Limited, Standard Chartered Bank (K) Limited, and Guardian Bank Kenya Limited. In addition to banking and conveyancing, Paul has significant experience in corporate and commercial law, advising on mergers and acquisitions, joint ventures, capital markets, structured financing, intellectual property, aircraft leasing & financing, and energy law. He has successfully acted for leading Kenyan and international corporate clients.', 
 E'Bank Securities & Conveyancing\nReal Estate Transactions\nCorporate & Commercial Law\nMergers & Acquisitions\nJoint Ventures\nCapital Markets & Structured Financing\nIntellectual Property Law\nAircraft Leasing & Financing\nEnergy Law', 
 E'University of Nairobi - Bachelor of Laws (LL.B), 2009\nKenya School of Law - Postgraduate Diploma in Law, 2010', 
 E'Advocate of the High Court of Kenya (2011)\nMember of Law Society of Kenya', 
 'English, Swahili, Kikuyu', 
 true),

('Faith Simiyu', 
 'Co-Founder & Partner', 
 'Partners', 
 'Litigation & Dispute Resolution', 
 'https://i.postimg.cc/0N0wpyV7/Whats-App-Image-2025-11-11-at-00-32-53.jpg', 
 'faith@soklaw.co.ke', 
 '0205285048', 
 E'LLB (Hons)\nDiploma in Law\nCertified Public Secretary\nManagement & Customer Care Training', 
 '10+ years of legal practice', 
 E'Successfully led high-profile litigation and dispute resolution matters\nHeaded legal departments in top organizations (KTDA, REAL Insurance, UAP Insurance)\nPublished articles in professional and corporate magazines\nFounder of County Legal Aid Bureau (CLAB) CSR initiative\nActive member of the Law Society of Kenya and East African Law Society', 
 'Sospeter Opondo Aming''a is the Co-Founder and Managing Partner of the Firm, where he leads the Litigation and Dispute Resolution department with a steadfast commitment to justice and the best interests of his clients. With over a decade of experience in legal practice and a strong corporate background, he brings both strategic insight and genuine compassion to every case he handles. His expertise spans litigation and out-of-court settlements in employment disputes, commercial matters, and personal injury claims. Before establishing the firm, Sospeter held senior positions in leading organizations, including Kenya Tea Development Agency (KTDA), REAL Insurance Company Ltd, and UAP Insurance Company Ltd, where he rose to head the legal department. This blend of corporate and legal experience equips him with a deep understanding of both the technical and human aspects of complex disputes. Beyond the courtroom, Sospeter is passionate about mentorship and giving back. He founded the County Legal Aid Bureau (CLAB), the firm''s flagship Corporate Social Responsibility program, which works to make legal support accessible to underserved communities.', 
 E'Litigation & Dispute Resolution\nEmployment Law\nCommercial Law\nPersonal Injury Claims\nOut-of-Court Settlements\nCorporate Legal Advisory', 
 E'University of Nairobi - Bachelor of Laws (LLB)\nKenya School of Law - Postgraduate Diploma in Law\nCertified Public Secretary (CPS-K)\nSpecialized Training - Management & Customer Care', 
 E'Advocate of the High Court of Kenya\nMember of Law Society of Kenya\nMember of East African Law Society\nCertified Public Secretary of Kenya', 
 'English, Swahili, Luo', 
 true),

('Angela Omuya', 
 'Partner', 
 'Partners', 
 'Legal Audits, Compliance & Data Protection Consultancy', 
 'https://i.postimg.cc/SKQKDtNL/7X2A2822.jpg', 
 'angela@soklaw.co.ke', 
 '+254 700 123 457', 
 E'LLB (Hons)\nCPA-K', 
 '10+ years of legal and compliance practice', 
 E'Led legal audits and compliance reviews for SMEs, start-ups, NGOs, and government bodies\nGuided County Governments on constitutional and regulatory compliance\nServed as Legal Counsel to the Judiciary for 7 years, advising on complex disputes and tribunal appeals\nContributed to national law reform and governance through work with Transparency International\nActive mentor, children''s ministry worker, and volunteer life coach', 
 'Angela Omuya is a Partner at the Firm, where she leads the Legal Audits and Compliance practice. An Advocate of the High Court of Kenya and a Certified Public Accountant (CPA-K), she brings a rare blend of legal precision and regulatory insight to help non-profits, SMEs, start-ups, and government entities stay compliant while achieving their goals. Her work ranges from legal audits, data protection compliance, and due diligence to contract negotiation, dispute resolution, and governance advisory. Whether reviewing HR manuals, guiding County Governments on constitutional compliance, or helping organizations strengthen their operational frameworks, Angela delivers practical solutions that work in the real world. Her decade-long career includes seven years as Legal Counsel to the Judiciary, where she supported judges in resolving complex commercial, employment, and contractual disputes, and advised on tribunal appeals and arbitral award enforcement. This experience sharpened her analytical skills, deepened her grasp of compliance risks, and gave her unique insight into Kenya''s legal landscape. Earlier, she worked with Transparency International, contributing to the review and reform of laws aimed at strengthening governance and accountability. Passionate about protecting and empowering children, Angela serves as a children''s ministry worker at her church and volunteers as a life coach at MCE Children''s Centre. Outside the office, she is an avid reader, mentor, and lifelong learner, happiest when spending quality time with family and friends.', 
 E'Legal Audits & Compliance\nData Protection & Privacy\nDue Diligence & Governance Advisory\nContract Negotiation\nDispute Resolution\nRegulatory & Constitutional Compliance', 
 E'Bachelor of Laws (LLB)\nCertified Public Accountant (CPA-K)', 
 E'Advocate of the High Court of Kenya\nCertified Public Accountant (CPA-K)\nMember of Law Society of Kenya', 
 'English, Swahili', 
 true),

('Kennedy Muriuki Kiranga', 
 'Senior Associate', 
 'Associates', 
 'Litigation Management & Corporate Law', 
 'https://i.postimg.cc/c4q4VJLL/Whats-App-Image-2025-08-13-at-04-23-09.jpg', 
 'kennedy@soklaw.co.ke', 
 '+254 700 123 458', 
 E'LLB (Hons)\nDiploma in Law\nNotary Public\nCommissioner for Oaths', 
 '7+ years of legal experience, 5+ years in active practice', 
 E'Successfully managed litigation processes and improved turnaround times through technology adoption\nLed high-value commercial and corporate transactions, including post-COVID-19 tourism recovery debenture registration\nContributed to policy development, treaty review, and constitutional litigation at the Office of the Attorney General\nStrong corporate grounding through treasury operations internship at Citi N.A. Kenya', 
 'Kennedy Muriuki Kiranga is an Advocate of the High Court of Kenya, Notary Public, and Commissioner for Oaths with over seven years of legal experience and more than five years in active practice. As a Senior Associate at Simiyu, Opondo, Kiranga & Co. Advocates, he has built a solid track record in litigation, conveyancing, corporate law, and commercial transactions, serving a diverse clientele across Kenya. Kennedy''s expertise spans litigation management, contract drafting and negotiation, perfection of securities for lending institutions, and corporate compliance. He has successfully driven process improvements through technology adoption, improved turnaround times in litigation, and played a pivotal role in high-impact transactions, including debenture registration that supported the tourism sector''s recovery post-COVID-19. He has also worked with the Office of the Attorney General, contributing to policy development, treaty review, and constitutional litigation, and gained early corporate exposure through a treasury operations internship at Citi N.A. Kenya.', 
 E'Litigation Management\nCorporate Law\nConveyancing\nCommercial Transactions\nContract Drafting & Negotiation\nSecurities & Banking Compliance\nCorporate Governance', 
 E'University of Nairobi - Bachelor of Laws (LLB)\nKenya School of Law - Diploma in Law', 
 E'Advocate of the High Court of Kenya\nNotary Public\nCommissioner for Oaths\nMember of Law Society of Kenya', 
 'English, Swahili, Kikuyu', 
 true),

('Geoffrey Otieno', 
 'Associate Advocate', 
 'Associates', 
 'Civil, Criminal, Family & Corporate Law', 
 'https://i.postimg.cc/PqFdKX7h/7X2A2896.jpg', 
 'geoffrey@soklaw.co.ke', 
 '+254 700 123 459', 
 'LLB (Hons)', 
 '4 years of legal practice', 
 E'Provided legal drafting and research support in diverse practice areas\nAssisted in litigation and case preparation across civil and criminal matters\nDelivered reliable legal opinions and document reviews for clients\nRecognized for clarity and precision in complex legal drafting', 
 'Geoffrey Otieno is a charismatic lawyer with a Bachelor of Laws (LLB) from Kenyatta University. At Simiyu, Opondo, Kiranga & Co. Advocates, he specializes in legal research, drafting, and reviewing across a broad range of practice areas, including civil, criminal, succession, family and children, contract, land, and company law matters. With four years of legal experience, Geoffrey is committed to turning legal complexity into strategic advantage, offering clients practical and well-structured legal solutions.', 
 E'Civil Law\nCriminal Law\nSuccession Law\nFamily & Children Law\nContract Law\nLand Law\nCompany Law\nLegal Research & Drafting', 
 'Kenyatta University - Bachelor of Laws (LLB)', 
 E'Advocate of the High Court of Kenya\nMember of Law Society of Kenya', 
 'English, Swahili', 
 true),

('Loise Njeri Njoroge', 
 'Associate Advocate', 
 'Associates', 
 'Litigation, Corporate & Commercial Law', 
 'https://i.postimg.cc/Z5KYK43F/7X2A2863.jpg', 
 'loise@soklaw.co.ke', 
 '+254 700 123 460', 
 'LLB (Hons)', 
 '4+ years of legal practice', 
 E'Successfully managed diverse litigation matters\nProvided expert legal drafting and contract preparation\nSkilled in negotiations and case management\nRecognized for professionalism and client-focused solutions', 
 'Loise Njeri Njoroge is a dedicated Kenyan lawyer with a Bachelor of Laws degree and over four years of experience in legal practice. She is currently part of the legal team at SOK Law Advocates, where she specializes in litigation, legal drafting, corporate, and commercial law. At SOK Law Advocates, Loise has successfully handled diverse legal matters, providing expert advice, contract preparation, pleadings, negotiations, case management, and drafting legal documents with professionalism and diligence. She is committed to upholding the highest standards of integrity and delivering practical, results-driven legal solutions to meet clients'' needs.', 
 E'Litigation\nCorporate Law\nCommercial Law\nLegal Drafting\nContract Negotiation\nCase Management', 
 'Bachelor of Laws (LLB)', 
 E'Advocate of the High Court of Kenya\nMember of Law Society of Kenya', 
 'English, Swahili, Kikuyu', 
 true),

('Justus Njoroge', 
 'Conveyancing Clerk', 
 'Consultants', 
 'Conveyancing & Property Documentation', 
 'https://i.postimg.cc/ncYZgYW3/7X2A2853.jpg', 
 'justus@soklaw.co.ke', 
 '+254 700 123 461', 
 E'Diploma in Legal Studies\nCertificate in Conveyancing Practice', 
 '3+ years in conveyancing and property documentation', 
 E'Managed efficient processing of property transfer documents\nAssisted in complex conveyancing transactions and due diligence\nMaintained accurate property records and client documentation\nSupported attorneys in property law matters with precision and attention to detail', 
 'Justus Njoroge serves as a Conveyancing Clerk at SOK Law Advocates, bringing specialized expertise in property documentation and conveyancing processes. With a strong background in legal studies and focused training in conveyancing practice, he plays a crucial role in ensuring smooth property transactions for the firm''s clients. His attention to detail and thorough understanding of property law procedures make him an invaluable asset to the conveyancing department. Justus works closely with the legal team to prepare, review, and process all property-related documentation, ensuring compliance with legal requirements and timely completion of transactions.', 
 E'Conveyancing Procedures\nProperty Documentation\nTitle Search & Verification\nProperty Transfer Processing\nLegal Document Preparation\nProperty Records Management', 
 E'Diploma in Legal Studies\nCertificate in Conveyancing Practice', 
 E'Registered Conveyancing Clerk\nMember of Professional Legal Clerks Association', 
 'English, Swahili, Kikuyu', 
 true),

('Shallet Wangui Katiku', 
 'Receptionist', 
 'Assistants', 
 'Client Relations & Administrative Support', 
 'https://i.postimg.cc/FFVBQW9k/7-X2-A2882-1.jpg', 
 'shallet@soklaw.co.ke', 
 '+254 700 123 462', 
 E'Certificate in Customer Service\nDiploma in Business Administration', 
 '2+ years in client service and administrative support', 
 E'Maintained excellent client satisfaction through professional front-desk service\nEfficiently managed appointment scheduling and client communications\nProvided multilingual support to diverse clientele\nStreamlined office administrative processes for improved efficiency', 
 'Shallet Wangui Katiku is the welcoming face of SOK Law Advocates, serving as the firm''s Receptionist and first point of contact for clients. With her warm personality and professional approach, she ensures that every client receives exceptional service from the moment they walk through the door or call the office. Shallet brings strong administrative skills and customer service expertise to her role, managing appointment scheduling, client inquiries, and general office coordination with efficiency and care. Her multilingual abilities and cultural sensitivity make her particularly effective in serving the firm''s diverse clientele, contributing significantly to the positive client experience that SOK Law is known for.', 
 E'Client Relations\nAdministrative Support\nAppointment Scheduling\nMulti-line Phone Management\nOffice Coordination\nCustomer Service Excellence', 
 E'Diploma in Business Administration\nCertificate in Customer Service', 
 'Certified Customer Service Professional', 
 'English, Swahili, Kikuyu', 
 true);
