/*
  Seed Services Data

  Inserts all 10 legal services with complete information.
*/

INSERT INTO services (
  id, slug, title, icon, description, detailed_description, color, icon_color,
  overview, header_image, key_services,
  why_choose_us_1_title, why_choose_us_1_description,
  why_choose_us_2_title, why_choose_us_2_description,
  why_choose_us_3_title, why_choose_us_3_description,
  process_step_1_title, process_step_1_description,
  process_step_2_title, process_step_2_description,
  process_step_3_title, process_step_3_description,
  process_step_4_title, process_step_4_description,
  process_step_5_title, process_step_5_description,
  display_order
) VALUES
-- 1. Civil and Criminal Litigation
(
  'civil-criminal-litigation',
  'civil-criminal-litigation',
  'Civil and Criminal Litigation',
  'Scale',
  'Expert representation in civil disputes and criminal defense matters with proven track record in Kenyan courts.',
  'Comprehensive litigation services covering both civil and criminal matters with experienced trial lawyers.',
  'bg-blue-50 border-blue-200',
  'text-blue-600',
  'Our litigation practice provides comprehensive representation in both civil and criminal matters. We handle complex disputes with strategic thinking and aggressive advocacy to achieve favorable outcomes for our clients.',
  'https://images.pexels.com/photos/5668882/pexels-photo-5668882.jpeg?auto=compress&cs=tinysrgb&w=1200&h=600&fit=crop',
  'Civil Litigation, Criminal Defense, Commercial Disputes, Contract Disputes, Tort Claims, Appeals, Injunctive Relief, Debt Recovery, Property Disputes, Constitutional Matters, Judicial Review, Class Action Suits',
  'Proven Track Record', 'Over 500 successful cases with extensive experience in Kenyan courts at all levels.',
  'Strategic Litigation', 'We develop comprehensive litigation strategies that consider both legal and business implications.',
  'Experienced Trial Lawyers', 'Our team includes seasoned trial lawyers with deep courtroom experience.',
  'Case Assessment', 'Comprehensive evaluation of your case merits and potential outcomes.',
  'Strategy Development', 'Development of tailored litigation strategy aligned with your objectives.',
  'Pre-trial Preparation', 'Thorough preparation including evidence gathering and witness preparation.',
  'Court Representation', 'Aggressive representation in court proceedings with experienced advocates.',
  'Post-judgment Support', 'Assistance with judgment enforcement and appeals if necessary.',
  1
),

-- 2. Alternative Dispute Resolution
(
  'alternative-dispute-resolution',
  'alternative-dispute-resolution',
  'Alternative Dispute Resolution (ADR) Arbitration, Mediation and Structured Negotiation',
  'Users',
  'Arbitration, mediation and structured negotiation services for efficient dispute resolution.',
  'Cost-effective dispute resolution through arbitration, mediation and structured negotiation processes.',
  'bg-green-50 border-green-200',
  'text-green-600',
  'Our ADR practice offers efficient alternatives to traditional litigation, helping clients resolve disputes through arbitration, mediation, and structured negotiation processes that save time and costs.',
  'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=1200&h=600&fit=crop',
  'Commercial Arbitration, Family Mediation, Workplace Mediation, Construction Arbitration, International Arbitration, Structured Negotiation, Conciliation Services, Expert Determination, Settlement Conferences, Multi-party Mediation, Online Dispute Resolution, Arbitrator Services',
  'Certified Mediators', 'Our team includes certified mediators and arbitrators with extensive ADR experience.',
  'Cost-Effective Solutions', 'ADR processes typically cost less and resolve faster than traditional litigation.',
  'Confidential Process', 'ADR proceedings are private and confidential, protecting your business interests.',
  'Dispute Analysis', 'Assessment of the dispute and recommendation of appropriate ADR method.',
  'Process Selection', 'Selection of the most suitable ADR process for your specific situation.',
  'Preparation', 'Thorough preparation of your case for the ADR proceedings.',
  'ADR Proceedings', 'Skilled representation during arbitration, mediation or negotiation.',
  'Implementation', 'Assistance with implementation and enforcement of ADR outcomes.',
  2
),

-- 3. Commercial and Corporate Law
(
  'commercial-corporate-law',
  'commercial-corporate-law',
  'Commercial and Corporate Law',
  'Building',
  'Comprehensive corporate legal services including company formation, governance, and commercial transactions.',
  'Expert corporate legal services for businesses of all sizes, ensuring compliance and strategic growth.',
  'bg-purple-50 border-purple-200',
  'text-purple-600',
  'Our commercial and corporate law practice provides comprehensive legal services to businesses across Kenya. We assist companies in navigating complex regulatory environments and structuring transactions for growth.',
  'https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?auto=compress&cs=tinysrgb&w=1200&h=600&fit=crop',
  'Company Formation, Corporate Governance, Mergers & Acquisitions, Joint Ventures, Commercial Contracts, Securities Law, Corporate Restructuring, Due Diligence, Regulatory Compliance, Board Advisory, Shareholder Agreements, Corporate Finance',
  'Business-Focused Approach', 'We understand business needs and provide practical legal solutions.',
  'Regulatory Expertise', 'Deep knowledge of Kenyan corporate law and regulatory requirements.',
  'Transaction Experience', 'Extensive experience in complex commercial transactions and deals.',
  'Business Consultation', 'Understanding your business objectives and legal requirements.',
  'Legal Structure', 'Designing optimal legal structures for your business operations.',
  'Documentation', 'Preparation of all necessary corporate and commercial documents.',
  'Implementation', 'Execution of corporate strategies and transaction completion.',
  'Ongoing Support', 'Continuous legal support for corporate governance and compliance.',
  3
),

-- 4. Bank Securities, Conveyancing and Real Estate Law
(
  'bank-securities-conveyancing-real-estate',
  'bank-securities-conveyancing-real-estate',
  'Bank Securities, Conveyancing and Real Estate Law',
  'Home',
  'Property transactions, land disputes, conveyancing, and banking securities legal services.',
  'Comprehensive real estate and banking securities services covering all aspects of property law.',
  'bg-orange-50 border-orange-200',
  'text-orange-600',
  'Our real estate and banking securities practice covers all aspects of property law and banking securities in Kenya. We provide comprehensive services for property transactions and banking security arrangements.',
  'https://images.pexels.com/photos/280229/pexels-photo-280229.jpeg?auto=compress&cs=tinysrgb&w=1200&h=600&fit=crop',
  'Property Conveyancing, Land Title Verification, Banking Securities, Mortgage Documentation, Lease Agreements, Property Development, Land Disputes, Security Perfection, Property Finance, Real Estate Investment, Landlord-Tenant Law, Zoning Applications',
  'Local Expertise', 'Deep understanding of Kenyan land law and banking regulations.',
  'Due Diligence Excellence', 'Thorough property searches and security verification processes.',
  'Banking Relationships', 'Strong relationships with major banks and financial institutions.',
  'Property/Security Search', 'Comprehensive verification of property titles and security interests.',
  'Due Diligence', 'Thorough investigation of legal and financial aspects.',
  'Documentation', 'Preparation of all necessary legal documents and agreements.',
  'Registration', 'Handling registration with relevant authorities and institutions.',
  'Post-transaction Support', 'Ongoing support for property management and security enforcement.',
  4
),

-- 5. Employment and Labour Law
(
  'employment-labour-law',
  'employment-labour-law',
  'Employment and Labour Law',
  'Briefcase',
  'Employment contracts, workplace disputes, labor relations, and human resources legal guidance.',
  'Comprehensive employment law services for both employers and employees, ensuring compliance with Kenyan labor laws.',
  'bg-pink-50 border-pink-200',
  'text-pink-600',
  'Our employment and labour law practice serves both employers and employees in navigating the complex landscape of Kenyan labor law and employment regulations.',
  'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=1200&h=600&fit=crop',
  'Employment Contracts, Workplace Policies, Disciplinary Procedures, Wrongful Termination, Discrimination Claims, Wage and Hour Issues, Workers Compensation, Union Relations, Employment Compliance, Executive Compensation, Non-compete Agreements, Workplace Safety',
  'Dual Perspective', 'We represent both employers and employees with balanced expertise.',
  'Regulatory Knowledge', 'Up-to-date knowledge of Kenyan employment law and regulations.',
  'Practical Solutions', 'Business-oriented solutions to employment challenges.',
  'Employment Consultation', 'Assessment of employment issues and legal options available.',
  'Legal Analysis', 'Analysis of employment contracts, policies, and applicable laws.',
  'Strategy Development', 'Development of strategic approach to resolve employment matters.',
  'Implementation', 'Implementation through negotiation, mediation, or litigation.',
  'Compliance Support', 'Ongoing support to ensure compliance and prevent future issues.',
  5
),

-- 6. Family Law
(
  'family-law',
  'family-law',
  'Family Law',
  'Heart',
  'Divorce proceedings, child custody, adoption, matrimonial property, and family dispute resolution.',
  'Compassionate and professional family law services handling sensitive matters with discretion.',
  'bg-red-50 border-red-200',
  'text-red-600',
  'Our family law practice provides compassionate legal services for families, handling sensitive matters with discretion while prioritizing the best interests of children and families.',
  'https://images.pexels.com/photos/1648776/pexels-photo-1648776.jpeg?auto=compress&cs=tinysrgb&w=1200&h=600&fit=crop',
  'Divorce and Separation, Child Custody, Child Support, Adoption Proceedings, Matrimonial Property, Prenuptial Agreements, Domestic Violence, Guardianship, Paternity Issues, Family Mediation, Succession Planning, Marriage Contracts',
  'Compassionate Approach', 'Understanding and supportive guidance through difficult family matters.',
  'Child-Focused', 'Always prioritizing the best interests of children in all proceedings.',
  'Confidential Service', 'Strict confidentiality and discrete handling of sensitive matters.',
  'Confidential Consultation', 'Private consultation to understand your family situation and needs.',
  'Case Preparation', 'Gathering necessary documentation and evidence for your case.',
  'Negotiation', 'Attempting amicable agreements through negotiation and mediation.',
  'Court Proceedings', 'Professional representation when court intervention is necessary.',
  'Post-decree Support', 'Ongoing support for enforcement and modification of orders.',
  6
),

-- 7. Consultancy
(
  'consultancy',
  'consultancy',
  'Consultancy',
  'HelpCircle',
  'Legal consultancy services providing strategic advice and guidance across various legal matters.',
  'Professional legal consultancy services offering strategic guidance and expert advice.',
  'bg-indigo-50 border-indigo-200',
  'text-indigo-600',
  'Our consultancy services provide strategic legal advice and guidance to individuals, businesses, and organizations across various legal matters and industries.',
  'https://images.pexels.com/photos/3184430/pexels-photo-3184430.jpeg?auto=compress&cs=tinysrgb&w=1200&h=600&fit=crop',
  'Legal Strategy Consulting, Risk Assessment, Compliance Consulting, Business Advisory, Legal Audits, Policy Development, Training Services, Legal Research, Regulatory Guidance, Contract Advisory, Dispute Prevention, Legal Opinions',
  'Strategic Thinking', 'We provide strategic legal advice that aligns with your business objectives.',
  'Industry Knowledge', 'Deep understanding of various industries and their legal requirements.',
  'Proactive Approach', 'Focus on preventing legal issues before they become problems.',
  'Needs Assessment', 'Understanding your specific consultancy needs and objectives.',
  'Analysis', 'Comprehensive analysis of your legal and business situation.',
  'Strategy Development', 'Development of tailored strategies and recommendations.',
  'Implementation Support', 'Guidance and support during strategy implementation.',
  'Ongoing Advisory', 'Continuous advisory support and strategy refinement.',
  7
),

-- 8. Health and Medical Law
(
  'health-medical-law',
  'health-medical-law',
  'Health and Medical Law',
  'Heart',
  'Healthcare law, medical malpractice, regulatory compliance, and healthcare facility legal services.',
  'Specialized legal services for healthcare providers, medical professionals, and healthcare institutions.',
  'bg-green-50 border-green-200',
  'text-green-600',
  'Our health and medical law practice provides specialized legal services to healthcare providers, medical professionals, and healthcare institutions across Kenya.',
  'https://images.pexels.com/photos/4021775/pexels-photo-4021775.jpeg?auto=compress&cs=tinysrgb&w=1200&h=600&fit=crop',
  'Medical Malpractice Defense, Healthcare Regulatory Compliance, Medical Licensing, Healthcare Contracts, Patient Rights, Medical Ethics, Healthcare Facility Licensing, Pharmaceutical Law, Medical Device Regulation, Healthcare Employment, Medical Records, Healthcare Disputes',
  'Medical Knowledge', 'Understanding of medical practices and healthcare regulations.',
  'Regulatory Expertise', 'Deep knowledge of healthcare regulatory requirements in Kenya.',
  'Professional Network', 'Strong relationships with medical professionals and institutions.',
  'Healthcare Assessment', 'Assessment of healthcare legal and regulatory requirements.',
  'Compliance Review', 'Review of current compliance with healthcare regulations.',
  'Risk Mitigation', 'Development of strategies to mitigate healthcare legal risks.',
  'Documentation', 'Preparation of healthcare policies, contracts, and procedures.',
  'Ongoing Support', 'Continuous support for healthcare compliance and legal matters.',
  8
),

-- 9. Finance and Banking Law
(
  'finance-banking-law',
  'finance-banking-law',
  'Finance and Banking Law',
  'DollarSign',
  'Banking regulations, financial services law, fintech compliance, and financial institution legal services.',
  'Comprehensive legal services for banks, financial institutions, and fintech companies.',
  'bg-blue-50 border-blue-200',
  'text-blue-600',
  'Our finance and banking law practice provides comprehensive legal services to banks, financial institutions, fintech companies, and clients with financial legal needs.',
  'https://images.pexels.com/photos/4386321/pexels-photo-4386321.jpeg?auto=compress&cs=tinysrgb&w=1200&h=600&fit=crop',
  'Banking Regulations, Financial Services Licensing, Fintech Compliance, Securities Law, Capital Markets, Banking Litigation, Financial Contracts, Regulatory Compliance, Anti-Money Laundering, Consumer Finance, Investment Advisory, Financial Restructuring',
  'Financial Expertise', 'Deep understanding of financial services and banking regulations.',
  'Regulatory Knowledge', 'Up-to-date knowledge of financial regulatory requirements.',
  'Industry Relationships', 'Strong relationships with financial regulators and institutions.',
  'Financial Assessment', 'Assessment of financial legal and regulatory requirements.',
  'Compliance Strategy', 'Development of financial compliance and regulatory strategy.',
  'Documentation', 'Preparation of financial agreements and regulatory filings.',
  'Regulatory Liaison', 'Liaison with financial regulators and authorities.',
  'Ongoing Compliance', 'Continuous support for financial compliance and regulations.',
  9
),

-- 10. Insurance and Personal Injury Law
(
  'insurance-personal-injury',
  'insurance-personal-injury',
  'Insurance and Personal Injury Law',
  'Shield',
  'Insurance claims, personal injury litigation, motor vehicle accidents, and insurance coverage disputes.',
  'Comprehensive legal services for insurance matters and personal injury claims.',
  'bg-red-50 border-red-200',
  'text-red-600',
  'Our insurance and personal injury practice provides comprehensive legal services for insurance claims, personal injury litigation, and insurance coverage disputes.',
  'https://images.pexels.com/photos/5668858/pexels-photo-5668858.jpeg?auto=compress&cs=tinysrgb&w=1200&h=600&fit=crop',
  'Personal Injury Claims, Motor Vehicle Accidents, Insurance Coverage Disputes, Workers Compensation, Medical Malpractice, Product Liability, Wrongful Death, Insurance Bad Faith, Disability Claims, Property Insurance, Professional Liability, Insurance Defense',
  'Insurance Knowledge', 'Deep understanding of insurance law and coverage issues.',
  'Trial Experience', 'Extensive trial experience in personal injury and insurance cases.',
  'Client Advocacy', 'Strong advocacy for clients against insurance companies.',
  'Claim Assessment', 'Comprehensive assessment of insurance claims and personal injury cases.',
  'Investigation', 'Thorough investigation of facts and circumstances.',
  'Negotiation', 'Skilled negotiation with insurance companies and opposing parties.',
  'Litigation', 'Aggressive litigation when fair settlement cannot be reached.',
  'Recovery', 'Assistance with claim recovery and settlement implementation.',
  10
);
